### ISSUE TITLE
API Troubles

### ISSUE THREAD

**Issue by chilldeleuze** [ChausseBenjamin/Inbox-for-Todoist#4]
Unfortunately the widget isn't working for me. I suspect it's unable to connect to todoist.

I noticed that my todoist.cache file only contains the string:

`Ä]q.` 

I deleted it, tried refreshing my API-Token, tried to just use a random string as a Token, it always produces the same cache file.

**Comment by ChausseBenjamin** [comment]
Okay, 

I'll be glad to help!

First off I just want to check a couple things with you:
-   Do you have python 3 installed ([https://github.com/ChausseBenjamin/Inbox-for-Todoist#installing-python-3](https://github.com/ChausseBenjamin/Inbox-for-Todoist#installing-python-3))
-   Did you install todoist's API [https://github.com/ChausseBenjamin/Inbox-for-Todoist#installing-todoists-python-package](https://github.com/ChausseBenjamin/Inbox-for-Todoist#installing-todoists-python-package)

If so, could you open up a terminal window and type in (one line at a time, return between each, enter four spaces for tabs):

    python3

Then:

    from todoist.api import TodoistAPI
        api = TodoistAPI('ENTER_YOUR_TOKEN_HERE')
        api.sync()  # initial sync

Replace ENTER_YOUR_TOKEN_HERE with your own token, keep the ' on each side.
Can you tell me what happens then? Todoist's API might be blocked by your firewall and I just want to be sure...

Afterwards, check if typing `print(api.state['items'])` give you a block of text containing your todoist items and all their information.

**Comment by ChausseBenjamin** [comment]
Closing due to lack of response.
